import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { fromHex } from '../src/lib/bytes';
import { NOTE_REC, OFF, PATTERN_BANK_SIZE, PATTERN_COUNT, PATTERN_SIZE, STEP_COUNT, TRACK_COUNT, TRACK_REC } from '../src/project/layout';

/** Loads a fixture generated by tools/fixtures/generate_fixtures.py (never hand-edited). */
export function fixture<T>(name: string): T {
  return JSON.parse(readFileSync(new URL(`./fixtures/${name}.json`, import.meta.url), 'utf8')) as T;
}

export const hex = fromHex;
export const sha256 = (data: Uint8Array): string => createHash('sha256').update(data).digest('hex');

/** Same deterministic "empty" bank as generate_fixtures.py blank_bank(). */
export function blankBank(): Uint8Array {
  const data = new Uint8Array(PATTERN_BANK_SIZE);
  for (let p = 0; p < PATTERN_COUNT; p++) {
    for (let s = 0; s < STEP_COUNT; s++) {
      for (let slot = 0; slot < OFF.NOTE_SLOTS_PER_STEP; slot++) {
        data[p * PATTERN_SIZE + OFF.NOTES + (s * OFF.NOTE_SLOTS_PER_STEP + slot) * OFF.NOTE_RECORD_SIZE + NOTE_REC.NOTE] = 0xff;
      }
    }
    for (let t = 0; t < TRACK_COUNT; t++) data[p * PATTERN_SIZE + t * OFF.TRACK_RECORD_SIZE + TRACK_REC.STEP_COUNT] = 16;
  }
  return data;
}

/** Deterministic pseudo-random bytes (xorshift32). */
export function randomBytes(length: number, seed = 0x0b2): Uint8Array {
  const out = new Uint8Array(length);
  let x = seed >>> 0 || 1;
  for (let i = 0; i < length; i++) {
    x ^= x << 13; x >>>= 0;
    x ^= x >>> 17;
    x ^= x << 5; x >>>= 0;
    out[i] = x & 0xff;
  }
  return out;
}

import { decodeFrame } from '../src/midi/frame';
import { decompress } from '../src/midi/zlib';
import { concat } from '../src/lib/bytes';
import { unwrap } from '../src/lib/result';

/**
 * Deflate output is NOT canonical: pako (zlib 1.2.x port) and CPython's zlib 1.3
 * can emit different — equally valid — compressed bytes for the same input.
 * So compressed payloads are compared on their *inflated* content, and frame
 * structure (ids, headers, chunk sizes) is compared separately.
 */
export function inflateFrame(frame: Uint8Array): { id: number; content: Uint8Array } {
  const f = unwrap(decodeFrame(frame));
  return { id: f.messageId, content: unwrap(decompress(f.payload)) };
}

export interface PatternFramesSummary {
  ids: number[];
  headers: string[];
  chunkSizes: number[];
  content: Uint8Array;
}

export function summarisePatternFrames(frames: Uint8Array[]): PatternFramesSummary {
  const decoded = frames.map((f) => unwrap(decodeFrame(f)));
  return {
    ids: decoded.map((d) => d.messageId),
    headers: decoded.map((d) => Array.from(d.payload.subarray(0, 6), (b) => b.toString(16).padStart(2, '0')).join('')),
    chunkSizes: decoded.map((d) => d.payload.length - 6),
    content: unwrap(decompress(concat(decoded.map((d) => d.payload.subarray(6))))),
  };
}
